
(function(){
  const $=s=>document.querySelector(s);
  function toast(t){let el=$('#avToast')||document.querySelector('.av-toast');if(!el)return;el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
  function updateSummary(){let f=$('#addVisitorForm');if(!f)return;let full=[f.firstName?.value,f.middleName?.value,f.lastName?.value].filter(Boolean).join(' ');if($('#sumName'))$('#sumName').textContent=full||'—';if($('#sumDate'))$('#sumDate').textContent=f.visitDate?.value||'—';if($('#sumPurpose'))$('#sumPurpose').textContent=f.purpose?.value||'—';if($('#sumSource'))$('#sumSource').textContent=f.heard?.value||'—'}
  function countCompanions(){let body=$('#companionBody');let count=body?body.querySelectorAll('tr:not(#companionEmpty)').length:0;if($('#sumCompanions'))$('#sumCompanions').textContent=String(count);return count}
  function addCompanion(){let body=$('#companionBody'),empty=$('#companionEmpty');if(!body)return;if(empty)empty.remove();let tr=document.createElement('tr');tr.innerHTML='<td><input placeholder="Companion name"></td><td><input placeholder="Relationship"></td><td><input maxlength="10" pattern="[0-9]{10}" placeholder="Phone number"></td><td><button type="button" class="av-remove" title="Remove"><i class="fa-regular fa-trash-can"></i></button></td>';body.appendChild(tr);countCompanions();tr.querySelector('.av-remove').onclick=()=>{tr.remove();if(!body.querySelector('tr'))body.innerHTML='<tr id="companionEmpty"><td colspan="4"><div class="av-empty-icon"><i class="fa-solid fa-people-group"></i></div><span>No companions added yet.</span></td></tr>';countCompanions();};}
  function setToday(){let form=$('#addVisitorForm');if(!form)return;let today=new Date().toISOString().slice(0,10);if(form.visitDate&&!form.visitDate.value)form.visitDate.value=today;}
  document.addEventListener('DOMContentLoaded',()=>{let form=$('#addVisitorForm');setToday();updateSummary();$('#visitorReset')?.addEventListener('click',()=>{form?.reset();setToday();let body=$('#companionBody');if(body)body.innerHTML='<tr id="companionEmpty"><td colspan="4"><div class="av-empty-icon"><i class="fa-solid fa-people-group"></i></div><span>No companions added yet.</span></td></tr>';countCompanions();updateSummary();toast('Form reset')});$('#addCompanionBtn')?.addEventListener('click',addCompanion);form?.addEventListener('input',updateSummary);form?.addEventListener('change',updateSummary);form?.addEventListener('submit',e=>{e.preventDefault();if(!form.checkValidity()){form.reportValidity();return}toast('Visitor saved successfully');setTimeout(()=>location.href='visitor-management.html',700)});});
})();
