
(function(){
  const qs=(s,r=document)=>r.querySelector(s), qsa=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const setErr=(input,msg='This field is required')=>{input.closest('.input-wrap')?.classList.add('invalid'); const e=input.closest('.form-group')?.querySelector('.error-msg'); if(e)e.textContent=msg;};
  const clearErr=input=>{input.closest('.input-wrap')?.classList.remove('invalid'); const e=input.closest('.form-group')?.querySelector('.error-msg'); if(e)e.textContent='';};
  qsa('.toggle-pass').forEach(btn=>btn.onclick=()=>{const input=btn.closest('.input-wrap').querySelector('input'); input.type=input.type==='password'?'text':'password'; btn.classList.toggle('fa-eye'); btn.classList.toggle('fa-eye-slash');});
  qsa('.role-card').forEach(card=>card.onclick=()=>{qsa('.role-card').forEach(c=>c.classList.remove('active')); card.classList.add('active'); const h=qs('[name="role"]'); if(h)h.value=card.dataset.role||'';});
  qsa('.auth-form').forEach(form=>form.onsubmit=e=>{e.preventDefault(); let ok=true; qsa('input[required],select[required],textarea[required]',form).forEach(input=>{clearErr(input); if((input.type==='checkbox'&&!input.checked)||(input.type!=='checkbox'&&!String(input.value).trim())){ok=false; setErr(input)} if(input.type==='email'&&input.value&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(input.value)){ok=false; setErr(input,'Enter a valid email address')}}); const p=qs('[name="password"]',form), c=qs('[name="confirmPassword"]',form); if(p&&c&&p.value!==c.value){ok=false;setErr(c,'Passwords do not match')} if(ok){location.href=form.dataset.next||'dashboard.html'}});
  const pass=qs('[data-strength]'); function updateStrength(){if(!pass)return; const v=pass.value; const rules=[v.length>=8,/[A-Z]/.test(v),/\d/.test(v),/[^A-Za-z0-9]/.test(v)]; qsa('.rule').forEach((r,i)=>{const icon=r.querySelector('i'); if(icon) icon.className='fa-solid '+(rules[i]?'fa-circle-check':'fa-circle')}); qsa('.strength-bars span').forEach((b,i)=>b.classList.toggle('on',i<rules.filter(Boolean).length)); const label=qs('.strength-label'); if(label) label.textContent=rules.filter(Boolean).length>=4?'Strong':rules.filter(Boolean).length>=2?'Medium':'Weak';}
  if(pass){pass.addEventListener('input',updateStrength); updateStrength();}
  const otp=qsa('.otp-input'); otp.forEach((input,i)=>{input.addEventListener('input',()=>{input.value=input.value.replace(/\D/g,'').slice(0,1); if(input.value&&otp[i+1])otp[i+1].focus()}); input.addEventListener('keydown',e=>{if(e.key==='Backspace'&&!input.value&&otp[i-1])otp[i-1].focus()}); input.addEventListener('paste',e=>{e.preventDefault(); const text=(e.clipboardData||window.clipboardData).getData('text').replace(/\D/g,'').slice(0,otp.length); [...text].forEach((ch,j)=>{if(otp[j])otp[j].value=ch}); if(otp[Math.min(text.length,otp.length)-1]) otp[Math.min(text.length,otp.length)-1].focus();});});
  const otpForm=qs('.otp-form'); if(otpForm)otpForm.onsubmit=e=>{e.preventDefault(); if(otp.every(i=>i.value)) location.href=otpForm.dataset.next||'registration-success.html'; else alert('Please enter the 6-digit code.')};
  let seconds=42; const timer=qs('[data-timer]'); if(timer)setInterval(()=>{if(seconds>0){seconds--;timer.textContent='(00:'+String(seconds).padStart(2,'0')+')'}},1000);
})();
